### ISSUE TITLE
Hey, there is a lot of immersion breaking moments

### ISSUE THREAD

**Issue by sebastianN01** [Skull217/DDLCtVN#1] opened 2018-02-15 22:05 UTC
The game keeps on crashing in some places and i have to press ignore to continue from whatever place the script can allow me, this is really inconvenient. Are you going to be doing something about it?

**Comment by sebastianN01** [comment] 2018-02-15 22:55
Monika route is completely broken, ignoring the errors switches route into Sayori, and then somehow into yuris, then going back to sayoris. its all very wonky once the errors start popping up

**Comment by Skull217** [comment] 2018-02-16 02:04
Understood. The issue is being fixed; I'll let you know of any updates.

**Comment by sebastianN01** [comment] 2018-02-16 17:03
@Skull217 
[traceback.txt](https://github.com/Skull217/DDLCtVN/files/1732121/traceback.txt)

**Comment by Skull217** [comment] 2018-02-16 17:05
Make sure you're using the latest download, and a clean install of DDLC

**Comment by sebastianN01** [comment] 2018-02-16 17:06
yeap, did both, and a clean save file, since another one was detected

**Comment by Skull217** [comment] 2018-02-16 17:10
I still don't think that's latest. Check monikaroute.rpy, you'll notice that line 1854 no longer references any "monikaroute" variable

**Comment by Skull217** [comment] 2018-02-16 17:10
On the git page, I mean.

**Comment by sebastianN01** [comment] 2018-02-16 17:15
yes, sorry. 1.2.6 that fixes it. :) great going man, after you fix some stuff its going to be a great memorable mod.

Heres a feedback about writing, dont capitalize whole words when i CAN think up in my mind how exactly the characters are talking to each other, its not necessary to do it EVERY few lines of dialogue.

**Comment by Skull217** [comment] 2018-02-16 17:17
I feel like every important error has been completely fixed in 1.2.6, but that remains to be fully seen.

I'll keep the writing mechanics in mind, but I feel like using it is strictly for emphasis. If I want something TO be emphasized, it gets used.

Anyway, I'll close the issue.

**Closed by Skull217** 2018-02-16 17:17 UTC
